on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            @DutraGames merge this PR please.
          reactions: rocket, +1
          github-token: ${{ secrets.SEMATIC }}
